INSERT INTO Contratos (NumContrato, FechaDeFirma, Contratista, Identificacion, ConfiguracionJuridica, CapacidadDelContratista, ModalidadDelProceso, ClaseDeContrato, ObjetoSuscripcion, ValorInicial, FechaRegistroPtaInicial, PlazoEjecucionInicial, Dependencia, FechaInicio, FechaTerminacion, BancaMultilateral) VALUES
('DNP-291-09', '18 mayo 2009', 'ECONOMETRÍA S.A.', '860065102-2', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'El consultor prestará los servicios para la Revisión de la metodología tarifaria para el transporte de derivados de petróleo en poliductos, y establecimiento de las tasas de remuneración de los activos para el transporte de crudos por oleoductos y de derivados por poliductos (los “Servicios”) que se especifican en el anexo A, “Términos de referencia y alcance de los Servicios”, que forman parte integral de este contrato.

El consultor encomendará la prestación de los Servicios al personal que se enumera en el Anexo B, “Personal del Consultor”.

El consultor presentará los informes al Contratante e la forma y dentro de los plazos indicados en el Anexo C, “Obligación del Consultor de presentar informes”.
', '247000000', '18 mayo 2009', '6 MESES', 'Subdirector de Minas y Energía ', '18 mayo 2009', '18-noviembre-2009', 'BID'), 
('DNP-318-09', '08 junio 2009', 'VALUE PARTNERS ARGENTINA S.A', 'OTRO DUCUMENTO 307093512', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Análisis de condiciones para la implementación y desarrollo regulatorio de la portabilidad numérica en Colombia.', '540560000', '08 junio 2009', '5 MESES', 'Director de Infraestructura Y Energía Sostenible', '08 junio 2009', '07-noviembre-2009', 'BID'), 
('DNP-326-09', '18 junio 2009', 'PROJEKTA LIMITADA INGENIEROS CONSULTORES', '860531577-6', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Estudio para el centro de control de tránsito de la ciudad de Medellín', '396720000', '18 junio 2009', '6 MESES', 'Director de Infraestructura Y Energía Sostenible', '18 junio 2009', '17-diciembre-2009', 'BID'), 
('DNP-335-09', '30 junio 2009', 'INVARSSON Y ASOCIADOS LIMITADA', '900092433-4', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Definición del proceso de Integración de Transporte Masivo y Transporte Colectivo para el Áerea Metropolitana de centro occidente  - AMCO', '127252000', '30 junio 2009', '4 MESES', 'Director de Infraestructura y Energía Sostenible ', '30 junio 2009', '30-octubre-2009', 'BID'), 
('DNP-378-09', '21 julio 2009', 'UNIVERSIDAD DE LOS ANDES', '860007386-1', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Asesorar y acompañar al Departamento Nacional de Planeación, en el análisis de priorización de las estrategias de movilidad a implementar en la Región Capital Bogotá - Cundinamarca', '620000000', '21 julio 2009', '5,5 MESES', 'Director de Infraestructura y Energía Sostenible ', '21 julio 2009', '30-junio-2010', 'BID'), 
('DNP-384-09', '28 julio 2009', 'VALOR EN FINANZAS LTDA VALFINANZAS', '830072000-1', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Diseño de la estrategia de vinculación de capital privado para soluciones de infraestructura de sedes judiciales ', '342200000', '28 julio 2009', '24 MESES', 'Director de Justicia y Seguridad', '28 julio 2009', '28-julio-2011', 'BID'), 
('DNP-401-09', '11 agosto 2009', 'ADVANCED LOGISTIC GROUP S.A.', 'A58623141', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Realzar los estudios preparatorios para promover el desarrollo de una plataforma logística en el ámbito logístico del pacífico colombiano, que aglomere servicios logísticos de valor agregado y promueva la diversificación de los mismos en el área de influencia del apoyo.', '860598940', 'VIGENCIA FUTURA', '11 MESES', 'Director de Infraestructura y Energía Sostenible ', '12 agosto 2009', '11-julio-2010', 'BID'), 
('DNP-402-09', '12 agosto 2009', 'UNIVERSIDAD NACIONAL DE COLOMBIA', '899999063-3', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Asesoría y acompañamiento al Departamento Nacional de Planeación en el análisis de priorización de las estrategias de movilidad a implementar en la región Capital Bogotá Cundinamarca"', '380000000', '12 agosto 2009', '4 MESES Y 15 DIAS', 'Director de Infraestructura y Energía Sostenible ', '12 agosto 2009', '27-diciembre-2009', 'BID'), 
('DNP-411-09', '25 agosto 2009', 'UNIÓN TEMPORAL B&P SERVICIOS LTDA', '900103559-2', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Identificación y desarrollo de escenarios de vinculación de participación privada en el sector de agua potable y saneamiento básico en el marco de los Planes Departamentales de Agua.', '217457710', '25 agosto 2009', '18 SEMANAS', 'Director de Desarrollo Urbano y Política Ambiental ', '25 agosto 2009', '05-abril-2010', 'BID'), 
('DNP-415-09', '27 agosto 2009', 'ECONOMETRÍA S.A.', '860065102-2', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Análisis de las condiciones regulatorias, económicas y financieras, beneficios y riesgos de la participación público - privada en la atención integral a la primera infancia, en Colombia', '230337785', 'VIGENCIA FUTURA', '30 SEMANAS O 7 MESES Y 12 DIAS', 'Director de Desarrollo Social', '28 agosto 2009', '12-marzo-2010', 'BID'), 
('DNP-424-09', '28 agosto 2009', 'WORLD RESOURCES INSTITUTE', '521257057-', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Estudio de Evaluación Ex post para el Sistema de Transporte Masivo de Bogotá TransMilenio Fase I y II en el marco de los Objetivos descritos en el Anexo A ', '130000000', '28 agosto 2009', '12 SEMANAS', 'Director de Infraestructura y Energía Sostenible ', '28 agosto 2009', '28-noviembre-2009', 'BID'), 
('DNP-429-09', '02 septiembre 2009', 'Grupo de Gestión y Tecnología S.A', '800216579-2', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Estudio de Implementación del Administrador de Cuentas del Sistema de Intercambios Comerciales en Salud ', '484880000', 'VIGENCIA FUTURA', '30 SEMANAS O 7 MESES Y 17 DIAS', 'Director de Desarrollo Social', '02 septiembre 2009', '17-abril-2010', 'BID'), 
('DNP-436-09', '07 septiembre 2009', 'ZAGREB CONSULTORES LIMITADA', '76051760-7', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Diseño de un modelo de costos para la estructuración financiera de proyectos de telecomunicaciones sociales.', '368514864', '07 septiembre 2009', '26 SEMANAS', 'Subdirector de Telecomunicaciones', '07 septiembre 2009', '23-marzo-2010', 'BID'), 
('DNP-540-09', '06 noviembre 2009', 'UNIÓN TEMPORAL IVARSSON Y ASOCIADOS LTDA. Y LOGITRANS LTDA', '800220410-2', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Formulación del Plan Maestro de Movilidad del municipio de Riohacha', '231725879', '06 noviembre 2009', '182 DÍAS', 'Director de Infraestructura y Energía Sostenible', '06 noviembre 2009', '08-junio-2010', 'BID'), 
('DNP-541-09', '06 noviembre 2009', 'SISTEMAS ANDINOS DE INGENIERÍA Y PLANIFICACIÓN SAIP LTDA.', '830025769-4', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Formulación del Plan Maestro de Movilidad del municipio de Ocaña', '230387025', '06 noviembre 2009', '182 DÍAS', 'Director de Infraestructura y Energía Sostenible', '06 noviembre 2009', '20-mayo-2010', 'BID'), 
('DNP-542-09', '06 noviembre 2009', 'SISTEMAS ANDINOS DE INGENIERÍA Y PLANIFICACIÓN SAIP LTDA.', '830025769-4', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Apoyo a la implementación de los Sistemas Estratégicos de Transporte Público SETPs', '178590567', '06 noviembre 2009', '182 DÍAS', 'Director de Infraestructura y Energía Sostenible', '06 noviembre 2009', '20-mayo-2010', 'BID'), 
('DNP-543-09', '09 noviembre 2009', 'UNIÓN TEMPORAL CAL Y MAYOR-GANNETT FLEMING MEXICO', '830023696-6', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Desarrollo conceptual del Plan Maestro y Arquitectura del ITS para Colombia.', '213440000', '09 noviembre 2009', '182 DÍAS', 'Director de Infraestructura y Energía Sostenible', '09 noviembre 2009', '23-mayo-2010', 'BID'), 
('DNP-553-09', '17 noviembre 2009', 'DISEÑO MERCADEO Y PUBLICIDAD SAS', '830097569-6', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Prestación de Servicios de Apoyo Logístico', 'Prestar los servicios de apoyo logístico para la realización del seminario de cierre  del Programa de Apoyo al Proceso de Participación Privada y Concesión en Infraestructura (PPCI II) en Colombia, organizado por el Departamento Nacionald e Planeación - Dirección de Infraestructura y Energía Sostenible (DIES) y la Gerencia de Participación Privada (GEINF).', '$72,492,746', '17 noviembre 2009', '22 DÍAS', 'Director de Infraestructura y Energía', '18 noviembre 2009', '10-diciembre-2009', 'BID'), 
('DNP-568-09', '20 noviembre 2009', 'MARKET TRUST LTDA.', '900238043-4', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Prestación de Servicios de Apoyo Logístico', 'Prestar los servicios de apoyo logístico para la realización del seminario de lanzamiento del piloto del proyecto de "Exportación por envíos postales para MIPYMES - Exportafácil" en Colombia, organizado por el Departamento Nacional de Planeación - Dirección de Infraestructura y Energía Sostenible (DIES).', '12483340', '20 noviembre 2009', '13 DÍAS', 'Subdirector de Telecomunicaciones de la Dirección de Infraestructura y Energía Sostenible', '20 noviembre 2009', '03-diciembre-2009', 'BID'), 
('DNP-569-09', '20 noviembre 2009', 'DÍGITOS Y DISEÑOS INDUSTRIA GRÁFICA LTDA.', '900068916-9', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Prestación de Servicios de Apoyo Logístico', 'Prestar los servicios de impresión y edición del material necesario para la realización del seminario del lanzamiento del piloto del proyecto de "Exportación por envíos postales para MIPYMES - Exportafácil" en Colombia, organizado por el Departamento Nacional de Planeación - Dirección de Infraestructura y Energía Sostenible (DIES).', '2718228', '20 noviembre 2009', '15 DÍAS', 'Subdirector de Telecomunicaciones de la Dirección de Infraestructura y Energía Sostenible', '24 noviembre 2009', '09-diciembre-2009', 'BID'), 
('DNP-574-09', '23 noviembre 2009', 'COOPERATIVA DE TRABAJO ASOCIADO SOLUCIONES DE AUDIO Y VIDEO SAVI', '830126649-2', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Prestación de Servicios de Apoyo Logístico', 'Realizar la producción y edición del VIDEO promocional del seminario de lanzamiento del piloto del proyecto de "Exportación por envíos postales para MIPYMES - Exportafácil" en Colombia, organizado por el Departamento Nacional de Planeación - Dirección de Infraestructura y Energía Sostenible (DIES).', '6380000', '24 noviembre 2009', '15 DÍAS', 'Subdirector de Telecomunicaciones de la Dirección de Infraestructura y Energía Sostenible', '24 noviembre 2009', '09-diciembre-2009', 'BID'), 
('DNP-575-09', '24 noviembre 2009', 'UNIÓN TEMPORAL GSD PLUS - LOGIT', '900215358-1', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Consultoría', 'Prestar los servicios para la evaluación técnica, económica y financiera de la viabilidad de usar la infraestructura de transporte de combustibles o construir una infraestructura nueva para el transporte de biocombustibles en Colombia.', '441287200', '24 noviembre 2009', '600 DÍAS', 'Subdirector de Minas y Energía', '24 noviembre 2009', '24-agosto-2010', 'BID'), 
('DNP-589-09', '01 diciembre 2009', 'STEER DAVIES & GLEAVE LIMITED SUCURSAL COLOMBIA', '830054097-7', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Prestación de Servicios', 'Prestar los servicios de capacitación de modelación de demanda de transporte en software EMME/3.', '17400000', '01 diciembre 2009', '5 SEMANAS', 'Director de Infraestructura y Energía Sostenible', '01 diciembre 2009', '31-diciembre-2009', 'BID'), 
('DNP-609-09', '21 diciembre 2009', 'PÁEZ Y ASOCIADOS COMPAÑÍA LTDA.', '860508480-4', 'Persona Jurídica', 'NO APLICA', 'Directa ', 'Contrato de Prestación de Servicios Profesionales', 'Efectuar la auditoría del Proyecto Programa de Apoyo al Proceso de Participación Privada y Concesión en Infraestructura Tercera Etapa (PPCI-3) y de la Cooperación Técnica Infrafund ATN/OC-10925-CO de acuerdo con los requerimientos establecidos en los Documentos AF-100 "Política del Banco sobre Auditoría de Proyectos y Entidades", AF-300 "Guías para la Preparación de Estados Financieros y Requisitos de Auditoría", y AF-400 "Términos de Referencia para la Auditoría Esterna de Proyectos Financiados por el BID".', '44341580', '22 diciembre 2009', 'C/0007/510/1000/4/0/10212/15/C', '', '30 diciembre 1899', '30-diciembre-1899', '')
