INSERT INTO SubComponentes (Sector_idSector, Descripcion)
VALUES 
('1', 'Estudio de preinversión en ciudades entre 250.000 y 600.000 habitantes (ciudades intermedias)'), 
('1', 'Estudio de preinversión para el mejoramiento del transporte interurbano (Cuencas)'), 
('1', 'Estudio de preinversión para el mejoramiento de la movilidad (gestión de tránsito)'), 
('1', 'Estudio de planes de movilidad en ciudades pequeñas'), 
('1', 'Estudio/conceptos técnicos metro de Bogotá'), 
('1', 'Estudio para establecer planes urbanos logísticos de carga'), 
('1', 'Estudio para fortalecimiento institucional y regulatorio'), 
('1', 'desarrollo de Estudio sectoriales de transporte'), 
('2', 'Estudio para el desarrollo institucional o regulatorio en los sectores de electricidad, hidrocarburos y minas.'), 
('3', 'Estudio para el desarrollo y fortalecimiento institucional y/o regulatorio en el sector de comunicaciones'), 
('4', 'Estudio de identificación de nuevos escenarios y de contratos de concesión para la participación privada del sector'), 
('5', 'Estudio para el desarrollo institucional y regulatorios para la participación privada en el sector Justicia'), 
('6', 'Estudio para el desarrollo institucional y regulatorios para la participación privada en el sector Salud'), 
('7', 'Estudio para el desarrollo institucional y regulatorios para la participación privada en el sector Primera Infancia'), 
('8', 'Estudio para el desarrollo institucional y regulatorios para la participación privada en el sector Educación'), 
('1', 'Proceso de estructuración de proyectos con participación privada contratados: Sector Transporte'), 
('2', 'Proceso de estructuración de proyectos con participación privada contratados: Sector Energía'), 
('3', 'Proceso de estructuración de proyectos con participación privada contratados: Sector Comunicaciones'), 
('4', 'Proceso de estructuración de proyectos con participación privada contratados: Sector Agua y Saneamiento'), 
('5', 'Proceso de estructuración de proyectos con participación privada contratados: Sector Justicia'), 
('7', 'Proceso de estructuración de proyectos con participación privada contratados: Sector Primera Infancia'), 
('1', 'Evaluación de las experiencias de participación privada sector Transporte'), 
('6', 'Evaluación de las experiencias de participación privada sector Salud'), 
('8', 'Evaluación de las experiencias de participación privada sector Educación');
